### ISSUE TITLE
VirClust web I cant download any 3A results or start 4A

### ISSUE THREAD

**Issue by Emmaruthstent** [CristinaMoraru/VirClust#7]
Hi

When I go to start step 3A the loading bar looks like it gets stuck for about 1 min and then disappears, it will not say finished successfully or have the green DONE. If I start step 3A again it will do the same thing but will say "Step 3A finished successfully with status 0." but won't have the green DONE. I can't download any 3A results or start 4A.

I'm not sure if my input files are the problem but step 1A and 2A do work. 

Hoping someone can identify what the problem might be!
Thanks!

**Comment by MonicaSteffi** [comment]
I am also facing the same issue. Were you able to solve it ?

**Comment by Emmaruthstent** [comment]
No not yet sadly.

**Comment by CristinaMoraru** [comment]
It was a server issue. It has been solved now and everything should be workign properly.
